/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/account/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Account Avatar */
    get: operations["get_account_avatar_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/email/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Email Request */
    post: operations["post_account_email_request_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/email/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Email Verify */
    post: operations["post_account_email_verify_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/language": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Language */
    post: operations["post_account_language_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/password/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Password Confirm */
    post: operations["post_account_password_confirm_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/password/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Password Request */
    post: operations["post_account_password_request_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/telegram/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Telegram Link */
    post: operations["post_account_telegram_link_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/account/telegram/notifications/probe": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Account Telegram Notifications Probe */
    post: operations["post_account_telegram_notifications_probe_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/ads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Ads List */
    get: operations["get_admin_ads_list_route"];
    put?: never;
    /** Admin Ad Create */
    post: operations["post_admin_ad_create_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/ads/{campaign_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Admin Ad Delete */
    delete: operations["delete_admin_ad_delete_route"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/ads/{campaign_id}/toggle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Ad Toggle */
    post: operations["post_admin_ad_toggle_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/appearance/favicon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Appearance Favicon Upload */
    post: operations["post_admin_appearance_favicon_upload_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/appearance/logo": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Appearance Logo Upload */
    post: operations["post_admin_appearance_logo_upload_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/backups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Backups List */
    get: operations["get_admin_backups_list_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/backups/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Backups Create */
    post: operations["post_admin_backups_create_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/backups/restore": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Backups Restore */
    post: operations["post_admin_backups_restore_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/backups/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Backups Upload */
    post: operations["post_admin_backups_upload_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/broadcast": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Broadcast */
    post: operations["post_admin_broadcast_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/broadcast/audience-counts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Broadcast Audience Counts */
    get: operations["get_admin_broadcast_audience_counts_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Health */
    get: operations["get_admin_health_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Logs */
    get: operations["get_admin_logs_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Me */
    get: operations["get_admin_me_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/panel/internal-squads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Panel Internal Squads */
    get: operations["get_admin_panel_internal_squads_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Payments List */
    get: operations["get_admin_payments_list_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/payments/export.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Payments Export */
    get: operations["get_admin_payments_export_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/payments/{payment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Payment Detail */
    get: operations["get_admin_payment_detail_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/promos": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Promos List */
    get: operations["get_admin_promos_list_route"];
    put?: never;
    /** Admin Promo Create */
    post: operations["post_admin_promo_create_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/promos/{promo_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Admin Promo Delete */
    delete: operations["delete_admin_promo_delete_route"];
    options?: never;
    head?: never;
    /** Admin Promo Update */
    patch: operations["patch_admin_promo_update_route"];
    trace?: never;
  };
  "/api/admin/settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Settings Get */
    get: operations["get_admin_settings_get_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Settings Patch */
    patch: operations["patch_admin_settings_patch_route"];
    trace?: never;
  };
  "/api/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Stats */
    get: operations["get_admin_stats_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/support/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Support Stats */
    get: operations["get_admin_support_stats_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/support/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Support Tickets */
    get: operations["get_admin_support_tickets_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/support/tickets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Support Ticket Detail */
    get: operations["get_admin_support_ticket_detail_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Support Ticket Patch */
    patch: operations["patch_admin_support_ticket_patch_route"];
    trace?: never;
  };
  "/api/admin/support/tickets/{id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Support Ticket Reply */
    post: operations["post_admin_support_ticket_reply_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/support/tickets/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Support Ticket Read */
    post: operations["post_admin_support_ticket_read_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin Sync */
    post: operations["post_admin_sync_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/tariffs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Tariffs Get */
    get: operations["get_admin_tariffs_get_route"];
    /** Admin Tariffs Save */
    put: operations["put_admin_tariffs_save_route"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/themes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Themes Get */
    get: operations["get_admin_themes_get_route"];
    /** Admin Themes Save */
    put: operations["put_admin_themes_save_route"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/translations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Translations Get */
    get: operations["get_admin_translations_get_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Admin Translations Patch */
    patch: operations["patch_admin_translations_patch_route"];
    trace?: never;
  };
  "/api/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin Users List */
    get: operations["get_admin_users_list_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin User Detail */
    get: operations["get_admin_user_detail_route"];
    put?: never;
    post?: never;
    /** Admin User Delete */
    delete: operations["delete_admin_user_delete_route"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/avatar": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin User Avatar */
    get: operations["get_admin_user_avatar_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/ban": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Ban */
    post: operations["post_admin_user_ban_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/extend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Extend */
    post: operations["post_admin_user_extend_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/hwid-device-limit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Hwid Device Limit */
    post: operations["post_admin_user_hwid_device_limit_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/message": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Message */
    post: operations["post_admin_user_message_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/message/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Message Preview */
    post: operations["post_admin_user_message_preview_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/premium-override": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Premium Override */
    post: operations["post_admin_user_premium_override_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/referrals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Admin User Referrals */
    get: operations["get_admin_user_referrals_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/regular-traffic-override": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Regular Traffic Override */
    post: operations["post_admin_user_regular_traffic_override_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/reset-trial": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Reset Trial */
    post: operations["post_admin_user_reset_trial_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/tariff": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Tariff */
    post: operations["post_admin_user_tariff_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/telegram-profile-link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Telegram Profile Link */
    post: operations["post_admin_user_telegram_profile_link_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/traffic-grant": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Admin User Traffic Grant */
    post: operations["post_admin_user_traffic_grant_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email/magic": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email Auth Magic */
    post: operations["post_email_auth_magic_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email/password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email Password Auth */
    post: operations["post_email_password_auth_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email/request": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email Auth Request */
    post: operations["post_email_auth_request_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/email/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Email Auth Verify */
    post: operations["post_email_auth_verify_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations["post_logout_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/telegram/nonce": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Telegram Oauth Nonce */
    post: operations["post_telegram_oauth_nonce_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Auth Token */
    post: operations["post_auth_token_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bootstrap */
    get: operations["get_bootstrap_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Devices */
    get: operations["get_devices_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices/disconnect": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disconnect Device */
    post: operations["post_disconnect_device_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/devices/topup-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Device Topup Options */
    get: operations["get_device_topup_options_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/i18n": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** I18N */
    get: operations["get_i18n_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["get_me_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Payment */
    post: operations["post_create_payment_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/payments/{payment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Payment Status */
    get: operations["get_payment_status_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/promo/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Promo */
    post: operations["post_apply_promo_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/referral/welcome-bonus/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Referral Welcome Bonus Claim */
    post: operations["post_referral_welcome_bonus_claim_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/subscription-guides": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Subscription Guides */
    get: operations["get_subscription_guides_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/subscription-guides/public/{share_token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Public Subscription Guides */
    get: operations["get_public_subscription_guides_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/subscription/auto-renew": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Subscription Auto Renew */
    post: operations["post_subscription_auto_renew_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/support/tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Support Tickets */
    get: operations["get_support_tickets_route"];
    put?: never;
    /** Support Create Ticket */
    post: operations["post_support_create_ticket_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/support/tickets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Support Ticket Detail */
    get: operations["get_support_ticket_detail_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/support/tickets/{id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Support Ticket Reply */
    post: operations["post_support_ticket_reply_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/support/tickets/{id}/read": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Support Ticket Read */
    post: operations["post_support_ticket_read_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/support/unread": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Support Unread */
    get: operations["get_support_unread_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tariffs/change": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tariff Change */
    post: operations["post_tariff_change_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tariffs/change-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tariff Change Options */
    get: operations["get_tariff_change_options_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tariffs/change-payment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Tariff Change Payment */
    post: operations["post_tariff_change_payment_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tariffs/topup-options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Tariff Topup Options */
    get: operations["get_tariff_topup_options_route"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/trial/activate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Activate Trial */
    post: operations["post_activate_trial_route"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdCreateBody */
    AdCreateBody: {
      /**
       * Cost
       * @default 0
       */
      cost: number;
      /** Source */
      source: string;
      /** Start Param */
      start_param: string;
    };
    /** AdOut */
    AdOut: {
      /** Cost */
      cost: number;
      /**
       * Created At
       * @default null
       */
      created_at: string | null;
      /** Id */
      id: number;
      /** Is Active */
      is_active: boolean;
      /**
       * Source
       * @default null
       */
      source: string | null;
      /**
       * Start Param
       * @default null
       */
      start_param: string | null;
      /** Stats */
      stats?: {
        [key: string]: unknown;
      };
    };
    /** AdToggleBody */
    AdToggleBody: {
      /**
       * Is Active
       * @default true
       */
      is_active: unknown;
    };
    /** AdminAdsListOut */
    AdminAdsListOut: {
      /** Campaigns */
      campaigns: components["schemas"]["AdOut"][];
      /** Totals */
      totals: {
        [key: string]: number;
      };
      $defs: {
        /** AdOut */
        AdOut: {
          /** Cost */
          cost: number;
          /**
           * Created At
           * @default null
           */
          created_at: string | null;
          /** Id */
          id: number;
          /** Is Active */
          is_active: boolean;
          /**
           * Source
           * @default null
           */
          source: string | null;
          /**
           * Start Param
           * @default null
           */
          start_param: string | null;
          /** Stats */
          stats?: {
            [key: string]: unknown;
          };
        };
      };
    };
    /** AdminHealthOut */
    AdminHealthOut: {
      /** Alerts */
      alerts: {
        [key: string]: unknown;
      }[];
      /**
       * Checked At
       * Format: date-time
       */
      checked_at: string;
    };
    /** AdminLogsListOut */
    AdminLogsListOut: {
      /** Logs */
      logs: components["schemas"]["LogOut"][];
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total */
      total: number;
      $defs: {
        /** LogOut */
        LogOut: {
          /**
           * Content
           * @default null
           */
          content: string | null;
          /**
           * Email
           * @default null
           */
          email: string | null;
          /**
           * Event Type
           * @default null
           */
          event_type: string | null;
          /** Is Admin Event */
          is_admin_event: boolean;
          /** Log Id */
          log_id: number;
          /**
           * Target User Id
           * @default null
           */
          target_user_id: number | null;
          /**
           * Target User Label
           * @default null
           */
          target_user_label: string | null;
          /**
           * Telegram First Name
           * @default null
           */
          telegram_first_name: string | null;
          /**
           * Telegram Username
           * @default null
           */
          telegram_username: string | null;
          /**
           * Timestamp
           * @default null
           */
          timestamp: string | null;
          /**
           * User Id
           * @default null
           */
          user_id: number | null;
          /**
           * User Label
           * @default null
           */
          user_label: string | null;
        };
      };
    };
    /** AdminMeOut */
    AdminMeOut: {
      /** Admin Ids */
      admin_ids: number[];
      /** User Id */
      user_id: number;
    };
    /** AdminPanelSyncOut */
    AdminPanelSyncOut: {
      /**
       * Details
       * @default null
       */
      details: unknown;
      /**
       * Last Sync Time
       * @default null
       */
      last_sync_time: string | null;
      /** Status */
      status: string;
      /** Subscriptions Synced */
      subscriptions_synced: number;
      /** Users Processed */
      users_processed: number;
    };
    /** AdminPaymentsListOut */
    AdminPaymentsListOut: {
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Payments */
      payments: components["schemas"]["PaymentOut"][];
      /** Total */
      total: number;
      $defs: {
        /** PaymentOut */
        PaymentOut: {
          /** Amount */
          amount: number;
          /**
           * Created At
           * @default null
           */
          created_at: string | null;
          /**
           * Currency
           * @default null
           */
          currency: string | null;
          /**
           * Description
           * @default null
           */
          description: string | null;
          /** Payment Id */
          payment_id: number;
          /**
           * Provider
           * @default null
           */
          provider: string | null;
          /**
           * Provider Payment Id
           * @default null
           */
          provider_payment_id: string | null;
          /**
           * Purchased Gb
           * @default null
           */
          purchased_gb: unknown;
          /**
           * Purchased Hwid Devices
           * @default null
           */
          purchased_hwid_devices: number | null;
          /**
           * Sale Mode
           * @default null
           */
          sale_mode: string | null;
          /**
           * Status
           * @default null
           */
          status: string | null;
          /**
           * Subscription Duration Months
           * @default null
           */
          subscription_duration_months: number | null;
          /**
           * Tariff Key
           * @default null
           */
          tariff_key: string | null;
          /**
           * Telegram Id
           * @default null
           */
          telegram_id: number | null;
          /**
           * Traffic Premium Gb
           * @default null
           */
          traffic_premium_gb: number | null;
          /**
           * Traffic Regular Gb
           * @default null
           */
          traffic_regular_gb: number | null;
          /** User Id */
          user_id: number;
          /** User Label */
          user_label: string;
        };
      };
    };
    /** AdminStatsOut */
    AdminStatsOut: {
      /** Currency Symbol */
      currency_symbol: string;
      /** Financial */
      financial: {
        [key: string]: unknown;
      };
      /**
       * Panel
       * @default null
       */
      panel: {
        [key: string]: unknown;
      } | null;
      panel_sync: components["schemas"]["AdminPanelSyncOut"];
      /**
       * Queue
       * @default null
       */
      queue: {
        [key: string]: unknown;
      } | null;
      /** Recent Payments */
      recent_payments: components["schemas"]["PaymentOut"][];
      /** Users */
      users: {
        [key: string]: unknown;
      };
      $defs: {
        /** AdminPanelSyncOut */
        AdminPanelSyncOut: {
          /**
           * Details
           * @default null
           */
          details: unknown;
          /**
           * Last Sync Time
           * @default null
           */
          last_sync_time: string | null;
          /** Status */
          status: string;
          /** Subscriptions Synced */
          subscriptions_synced: number;
          /** Users Processed */
          users_processed: number;
        };
        /** PaymentOut */
        PaymentOut: {
          /** Amount */
          amount: number;
          /**
           * Created At
           * @default null
           */
          created_at: string | null;
          /**
           * Currency
           * @default null
           */
          currency: string | null;
          /**
           * Description
           * @default null
           */
          description: string | null;
          /** Payment Id */
          payment_id: number;
          /**
           * Provider
           * @default null
           */
          provider: string | null;
          /**
           * Provider Payment Id
           * @default null
           */
          provider_payment_id: string | null;
          /**
           * Purchased Gb
           * @default null
           */
          purchased_gb: unknown;
          /**
           * Purchased Hwid Devices
           * @default null
           */
          purchased_hwid_devices: number | null;
          /**
           * Sale Mode
           * @default null
           */
          sale_mode: string | null;
          /**
           * Status
           * @default null
           */
          status: string | null;
          /**
           * Subscription Duration Months
           * @default null
           */
          subscription_duration_months: number | null;
          /**
           * Tariff Key
           * @default null
           */
          tariff_key: string | null;
          /**
           * Telegram Id
           * @default null
           */
          telegram_id: number | null;
          /**
           * Traffic Premium Gb
           * @default null
           */
          traffic_premium_gb: number | null;
          /**
           * Traffic Regular Gb
           * @default null
           */
          traffic_regular_gb: number | null;
          /** User Id */
          user_id: number;
          /** User Label */
          user_label: string;
        };
      };
    };
    /** LogOut */
    LogOut: {
      /**
       * Content
       * @default null
       */
      content: string | null;
      /**
       * Email
       * @default null
       */
      email: string | null;
      /**
       * Event Type
       * @default null
       */
      event_type: string | null;
      /** Is Admin Event */
      is_admin_event: boolean;
      /** Log Id */
      log_id: number;
      /**
       * Target User Id
       * @default null
       */
      target_user_id: number | null;
      /**
       * Target User Label
       * @default null
       */
      target_user_label: string | null;
      /**
       * Telegram First Name
       * @default null
       */
      telegram_first_name: string | null;
      /**
       * Telegram Username
       * @default null
       */
      telegram_username: string | null;
      /**
       * Timestamp
       * @default null
       */
      timestamp: string | null;
      /**
       * User Id
       * @default null
       */
      user_id: number | null;
      /**
       * User Label
       * @default null
       */
      user_label: string | null;
    };
    /** PaymentDetailOut */
    PaymentDetailOut: {
      /** Amount */
      amount: number;
      /**
       * Created At
       * @default null
       */
      created_at: string | null;
      /**
       * Currency
       * @default null
       */
      currency: string | null;
      /**
       * Description
       * @default null
       */
      description: string | null;
      /**
       * Idempotence Key
       * @default null
       */
      idempotence_key: string | null;
      /** Payment Id */
      payment_id: number;
      /**
       * Promo Code
       * @default null
       */
      promo_code: string | null;
      /**
       * Provider
       * @default null
       */
      provider: string | null;
      /**
       * Provider Payment Id
       * @default null
       */
      provider_payment_id: string | null;
      /**
       * Purchased Gb
       * @default null
       */
      purchased_gb: unknown;
      /**
       * Purchased Hwid Devices
       * @default null
       */
      purchased_hwid_devices: number | null;
      /**
       * Sale Mode
       * @default null
       */
      sale_mode: string | null;
      /**
       * Status
       * @default null
       */
      status: string | null;
      /**
       * Subscription Duration Months
       * @default null
       */
      subscription_duration_months: number | null;
      /**
       * Tariff Key
       * @default null
       */
      tariff_key: string | null;
      /**
       * Telegram Id
       * @default null
       */
      telegram_id: number | null;
      /**
       * Traffic Premium Gb
       * @default null
       */
      traffic_premium_gb: number | null;
      /**
       * Traffic Regular Gb
       * @default null
       */
      traffic_regular_gb: number | null;
      /**
       * Updated At
       * @default null
       */
      updated_at: string | null;
      /** User Id */
      user_id: number;
      /** User Label */
      user_label: string;
      /**
       * Yookassa Payment Id
       * @default null
       */
      yookassa_payment_id: string | null;
    };
    /** PaymentOut */
    PaymentOut: {
      /** Amount */
      amount: number;
      /**
       * Created At
       * @default null
       */
      created_at: string | null;
      /**
       * Currency
       * @default null
       */
      currency: string | null;
      /**
       * Description
       * @default null
       */
      description: string | null;
      /** Payment Id */
      payment_id: number;
      /**
       * Provider
       * @default null
       */
      provider: string | null;
      /**
       * Provider Payment Id
       * @default null
       */
      provider_payment_id: string | null;
      /**
       * Purchased Gb
       * @default null
       */
      purchased_gb: unknown;
      /**
       * Purchased Hwid Devices
       * @default null
       */
      purchased_hwid_devices: number | null;
      /**
       * Sale Mode
       * @default null
       */
      sale_mode: string | null;
      /**
       * Status
       * @default null
       */
      status: string | null;
      /**
       * Subscription Duration Months
       * @default null
       */
      subscription_duration_months: number | null;
      /**
       * Tariff Key
       * @default null
       */
      tariff_key: string | null;
      /**
       * Telegram Id
       * @default null
       */
      telegram_id: number | null;
      /**
       * Traffic Premium Gb
       * @default null
       */
      traffic_premium_gb: number | null;
      /**
       * Traffic Regular Gb
       * @default null
       */
      traffic_regular_gb: number | null;
      /** User Id */
      user_id: number;
      /** User Label */
      user_label: string;
    };
    /** PromoCreateBody */
    PromoCreateBody: {
      /** Bonus Days */
      bonus_days: number;
      /** Code */
      code: string;
      /** Max Activations */
      max_activations: number;
      /**
       * Valid Days
       * @default null
       */
      valid_days: unknown;
    };
    /** PromoOut */
    PromoOut: {
      /** Bonus Days */
      bonus_days: number;
      /** Code */
      code: string;
      /**
       * Created At
       * @default null
       */
      created_at: string | null;
      /**
       * Created By Admin Id
       * @default null
       */
      created_by_admin_id: number | null;
      /** Current Activations */
      current_activations: number;
      /** Id */
      id: number;
      /** Is Active */
      is_active: boolean;
      /** Max Activations */
      max_activations: number;
      /**
       * Valid Until
       * @default null
       */
      valid_until: string | null;
    };
    /** PromoUpdateBody */
    PromoUpdateBody: {
      /**
       * Bonus Days
       * @default null
       */
      bonus_days: number | null;
      /**
       * Is Active
       * @default null
       */
      is_active: unknown;
      /**
       * Max Activations
       * @default null
       */
      max_activations: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_account_avatar_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_email_request_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_email_verify_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_language_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_password_confirm_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_password_request_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_telegram_link_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_account_telegram_notifications_probe_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_ads_list_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminAdsListOut"];
        };
      };
    };
  };
  post_admin_ad_create_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdCreateBody"];
      };
    };
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            campaign: components["schemas"]["AdOut"];
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  delete_admin_ad_delete_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_ad_toggle_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdToggleBody"];
      };
    };
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_appearance_favicon_upload_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_appearance_logo_upload_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_backups_list_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_backups_create_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_backups_restore_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_backups_upload_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_broadcast_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_broadcast_audience_counts_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_health_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminHealthOut"];
        };
      };
    };
  };
  get_admin_logs_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminLogsListOut"];
        };
      };
    };
  };
  get_admin_me_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminMeOut"];
        };
      };
    };
  };
  get_admin_panel_internal_squads_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_payments_list_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminPaymentsListOut"];
        };
      };
    };
  };
  get_admin_payments_export_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/csv": string;
        };
      };
    };
  };
  get_admin_payment_detail_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        payment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
            payment: components["schemas"]["PaymentDetailOut"];
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_promos_list_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
            page: number;
            page_size: number;
            promos: components["schemas"]["PromoOut"][];
            total: number;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_promo_create_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromoCreateBody"];
      };
    };
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
            promo: components["schemas"]["PromoOut"];
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  delete_admin_promo_delete_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        promo_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  patch_admin_promo_update_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        promo_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PromoUpdateBody"];
      };
    };
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
            promo: components["schemas"]["PromoOut"];
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_settings_get_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  patch_admin_settings_patch_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_stats_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": ({
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          }) &
            components["schemas"]["AdminStatsOut"];
        };
      };
    };
  };
  get_admin_support_stats_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_support_tickets_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_support_ticket_detail_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  patch_admin_support_ticket_patch_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_support_ticket_reply_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_support_ticket_read_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_sync_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_tariffs_get_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  put_admin_tariffs_save_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_themes_get_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  put_admin_themes_save_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_translations_get_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  patch_admin_translations_patch_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_users_list_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_user_detail_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  delete_admin_user_delete_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_user_avatar_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_ban_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_extend_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_hwid_device_limit_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_message_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_message_preview_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_premium_override_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_admin_user_referrals_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_regular_traffic_override_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_reset_trial_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_tariff_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_telegram_profile_link_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_admin_user_traffic_grant_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_email_auth_magic_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_email_password_auth_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_email_auth_request_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_email_auth_verify_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_logout_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_telegram_oauth_nonce_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_auth_token_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_bootstrap_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_devices_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_disconnect_device_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_device_topup_options_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_i18n_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_me_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_create_payment_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_payment_status_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        payment_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_apply_promo_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_referral_welcome_bonus_claim_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_subscription_guides_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_public_subscription_guides_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        share_token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_subscription_auto_renew_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_support_tickets_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_support_create_ticket_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_support_ticket_detail_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_support_ticket_reply_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_support_ticket_read_route: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_support_unread_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_tariff_change_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_tariff_change_options_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_tariff_change_payment_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_tariff_topup_options_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  post_activate_trial_route: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description JSON response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @constant */
            ok: true;
          } & {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
